from pymongo import MongoClient
from pymongo.server_api import ServerApi
import os
from dotenv import load_dotenv
from pathlib import Path

# Load env variables from root
env_path = Path(__file__).parents[1] / '.env.local'
load_dotenv(dotenv_path=env_path)

MONGO_URI = os.getenv("MONGO_URI")

if not MONGO_URI or "mock" in MONGO_URI:
    print("❌ Error: Valid MONGO_URI not found in .env.local")
    exit(1)

client = MongoClient(MONGO_URI, server_api=ServerApi('1'))
db = client['salus_db']

def seed_data():
    print("🌱 Seeding Database...")
    
    # 1. Policies Collection
    policies_col = db['policies']
    policies_col.delete_many({})  # Clear existing
    
    sample_policies = [
        {
            "id": "88123456",
            "provider": "Sun Life Financial",
            "plan_name": "Gold Health Plus",
            "coverage": {
                "hospital_stay": {"percentage": 0.80, "limit": 5000},
                "ambulance": {"percentage": 1.0, "limit": 500},
                "drugs": {"percentage": 0.80, "deductible": 50}
            }
        },
        {
            "id": "88987654",
            "provider": "Manulife",
            "plan_name": "Standard Care",
            "coverage": {
                "hospital_stay": {"percentage": 0.70, "limit": 3000},
                "ambulance": {"percentage": 0.50, "limit": 250}
            }
        }
    ]
    policies_col.insert_many(sample_policies)
    print(f"✅ Inserted {len(sample_policies)} policies.")

    # 2. Laws Collection (for Vector Search)
    laws_col = db['laws']
    laws_col.delete_many({}) # Clear existing
    
    # NOTE: In a real app, these would have 'embedding' fields generated by an embedding model.
    # For the Hackathon, we will insert them and assume the Extractor node might just do keyword search 
    # OR we use the Atlas Vector Search feature.
    # To use Vector Search, these documents MUST have an 'embedding' array.
    # We will adding a placeholder 'embedding' field. In a real run, you'd generate this with Gemini Embeddings.
    
    sample_laws = [
        {
            "title": "Ontario Works Act, 1997",
            "section": "Health Benefits",
            "content": "Recipients of income assistance are eligible for drug coverage and dental care for children.",
            "region": "ON",
            "embedding": [0.0] * 768 # Placeholder 768-dim vector
        },
        {
            "title": "Canada Health Act",
            "section": "Universality",
            "content": "All insured persons of a province are entitled to the insured health services provided for by the plan on uniform terms and conditions.",
            "region": "Federal",
            "embedding": [0.0] * 768
        }
    ]
    laws_col.insert_many(sample_laws)
    print(f"✅ Inserted {len(sample_laws)} laws.")
    
    print("\n🎉 Database Seeded Successfully!")

if __name__ == "__main__":
    seed_data()
